INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1326, 'A&D', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1327, 'ABC', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1328, 'ActionSoft', 'ActionSoft  S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1329, 'ADA SOFT', 'Ada Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1330, 'Addsoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1331, 'Adeptus Code', 'Adeptus Code SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1332, 'ADSysCorp', 'ADSystem Corporation', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1333, 'AGAAK development SRL', 'AGAAK', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1334, 'AGEN', 'AgileEngineers', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1335, 'Agile Action', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1336, 'AGILESOFT', 'AGILESOFT', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1337, 'AiraSoft', 'AiraSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1338, 'Akira soft', 'Akira soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1339, 'AlfaSoft', 'AlfaSoft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1340, 'Altec SRL', 'Experiencia y alta tecnologia SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1341, 'ANDESOFT', 'ANDESOFT', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1342, 'Angel Fire', 'Angel Fire', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1343, 'ANKA SOFT', 'ANKA SOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1344, 'Answer', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1345, 'Ant Work', 'Ant Work SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1346, 'Aracorp', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1347, 'ARES', 'ARES S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1348, 'ARGOS', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1349, 'Arkano', 'Arkano', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1350, 'Aska', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1351, 'ASSI', 'ASSI', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1352, 'AT&P', 'AT&P SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1353, 'ATIS SRL', 'ATIS SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1354, 'Atiysoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1355, 'Atom', 'Atom Software SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1356, 'Authentic Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1357, 'B.TECTIS', 'BUSSINESS TECNO TIS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1358, 'B&B', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1359, 'Bastet S.R.L.', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1360, 'BeDevs S.R.L.', 'BeDevs S-R-L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1361, 'BERSASOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1362, 'BH Soft', 'Bit Hunter Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1363, 'Binary', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1364, 'Binarysoft', 'Binarysoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1365, 'Bit SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1366, 'BitDevs', 'BitDevs SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1367, 'Bittle SRL', 'Bittle SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1368, 'Black Cloud', 'Black Cloud S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1369, 'Blue Marlin S.R.L.', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1370, 'BolBuilder', 'BolBuilder SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1371, 'Bolivia soft', 'Bolivia soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1372, 'Boost Soft', 'Boost Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1373, 'BOS SA', 'Build Of System S.A', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1374, 'Bots'' System Teach', 'Bots'' System Teach.SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1375, 'Boy''s Code', 'Boy''s Code SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1376, 'BRAIN SOFT', 'BRAIN SOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1377, 'Brave Soft', 'Brave software solutions', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1378, 'Build Solutions', 'Build Solutions SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1379, 'Building Soft', 'Building Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1380, 'Burgos Soft', 'BURGOS SOFT S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1381, 'BUSSINESOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1382, 'C@DSOFT SRL', 'C@DSOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1383, 'Caesar asociados', 'Caesar asociados', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1384, 'CAMEL SOFT', 'CAMEL  SOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1385, 'Canguro soft srl', 'Canguro soft srl', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1386, 'CaniSoft SRL', 'CaniSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1387, 'Capsule', 'Capsule SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1388, 'CAS S.R.L.', 'Cochabamba Automática Soft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1389, 'Cassiopeia', 'Cassiopeia', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1390, 'Cativos', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1391, 'CDSA SRL', 'Consultora de desarrollo de software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1392, 'CEDSI', 'CEDSI', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1393, 'Cemdesoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1394, 'CENTAURO', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1395, 'Centersoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1396, 'Chameleon Code', 'Chameleon Code Software S.R.L', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1397, 'CHR SRL', 'Compumundo Hipermega Red SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1398, 'Cis sa', 'Cis sa', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1399, 'CISOFT', 'CISOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1400, 'CLASSSOFT SRL', 'CLASSSOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1401, 'Click', 'Click Soluciones Informáticas', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1402, 'Clicknet', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1403, 'ClubMorning', 'ClubMorning S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1404, 'Cochala-Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1405, 'CODEBREAKER', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1406, 'CodeCraze', 'CodeCraze SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1407, 'CodeFusion', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1408, 'Codemaster', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1409, 'CODESOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1410, 'Codesoft', 'Codesoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1411, 'Codesoft_srl', 'Codesoft_srl', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1412, 'Codigo Enigma S.R.L.', 'Codigo Enigma S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1413, 'Codigo Fuerte S.R.L.', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1414, 'COLECTIVO', 'COLECTIVO VIRTUAL SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1415, 'Colmena SRL', 'Colmena SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1416, 'comotusoft', 'Como Tu Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1417, 'Compusoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1418, 'CondeVela Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1419, 'Condor Technology', 'Condor Technology S.R.L', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1420, 'Conseinf', 'Conseinf', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1421, 'ControlZ', 'ControlZ', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1422, 'Corporación de Software y Tecnología SRL', 'CST', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1423, 'Cosinf', 'Consultora de Servicios Informáticos', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1424, 'Creasser SRL', 'Creasser SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1425, 'CREATIVE.SOFT777 S.R.L.', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1426, 'CREATIVESOFT', 'SOFTWARE CREATIVO', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1427, 'Cripher', 'CodeFusion SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1428, 'Crovz', 'Crovz', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1429, 'CSI', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1430, 'Csi', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1431, 'Csisi', 'Csisi', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1432, 'Csiv', 'Csiv', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1433, 'Cstidas', 'Cstidas', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1434, 'ctrl_alt_soft', 'ctrl_alt_soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1435, 'CTRLS SRL', 'Controlled Solutions SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1436, 'Cusco_system', 'Cusco_system', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1437, 'Cyber Nest', 'Cyber Nest SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1438, 'Cyber Systems', 'Cyber Systems', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1439, 'Cyborg Solutions LTD.', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1440, 'D.A.C. S.A', 'Dream Act Create S.A.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1441, 'D&D', 'Design & Development software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1442, 'DAD software', 'DAD software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1443, 'DarkSoft', 'DarkSoft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1444, 'Dastech', 'Dastech', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1445, 'Databyte', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1446, 'DDS', 'Digital Development Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1447, 'DEBUG', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1448, 'DecSoft', 'DecSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1449, 'DelfiNet', 'DelfiNet', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1450, 'Delfos SRL', 'Delfos Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1451, 'Demonnet', 'Demonnet', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1452, 'DEPSOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1453, 'DESIGNTEC', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1454, 'Desofin', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1455, 'DESOFT SRL', 'DESOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1456, 'DESOInf', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1457, 'Dessa', 'Desarrolladora de Software Aplicado', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1458, 'Dessoft ORION', 'Dessoft ORION', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1459, 'Dev Solutions ISC', 'DevSolutions Innovative Software Company SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1460, 'DevBOL', 'DevBol SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1461, 'Developer in open source', 'Developer in open source', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1462, 'DEVS', 'DEVS GROUP SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1463, 'DevSociety', 'Developer''s Society S.R.L', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1464, 'DEVSOFT SRL.', 'Developer Software SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1465, 'DevSol.SRL', 'DevSol.SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1466, 'DevSZ', 'Development Software Z', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1467, 'DFS SRL', 'Desarrollo de Fuertes Soluciones S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1468, 'DG', 'DevGenius S.R.L', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1469, 'DICOSOFT', 'diseño y consultoria de software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1470, 'Digital City', 'Digital City S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1471, 'DIGITAL CRAFTERS', 'DIGITAL CRAFTERS Inc. S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1472, 'DIGITAL SYSTEMS', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1473, 'DigitalSoft', 'DigitalSoft SA', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1474, 'Dim_soft', 'Dim_soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1475, 'Dinasoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1476, 'Dios', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1477, 'DIS', 'DIS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1478, 'DiverNet', 'DiverNert', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1479, 'DKS', 'DKS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1480, 'DOMINOSOFT SRL', 'DOMINOSOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1481, 'Dotpoint Soft.Srl', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1482, 'Dows', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1483, 'Drakko', 'Drakko srl', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1484, 'Dreams SRL', 'Dreams SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1485, 'Drsif', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1486, 'DS', 'Digital Strategies', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1487, 'DSA', 'DSA', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1488, 'DSAN', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1489, 'DSI', 'DSI', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1490, 'Dsisoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1491, 'Dsp', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1492, 'DTS', 'DTS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1493, 'DYANSOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1494, 'e & s SRL', 'e & s SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1495, 'EAGLESOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1496, 'EDAS', 'EDAS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1497, 'EDESSI', 'Empresa de Desarrollo de Sistemas y Servicios Informaticos', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1498, 'Editsoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1499, 'EDS SA', 'Empresa de Desarrollo de Software SA', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1500, 'EDSI', 'Empresa de Desarrollo de Sistemas Informáticos', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1501, 'EDSIN', 'Elite en Desarrollo Soluciones Informaticas', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1502, 'Edsj', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1503, 'EDSL', 'EDSL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1504, 'EDSODIA SRL', 'Empresa de Desarrollo de Software de Implementación Actual SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1505, 'Edti', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1506, 'Eficient', 'Eficient', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1507, 'Egroup', 'e-group srl', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1508, 'EIDS', 'EIDS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1509, 'EKEKO', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1510, 'Elysium', 'Elysium S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1511, 'Emagic', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1512, 'Emcosis', 'emcosis srl', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1513, 'emcosoft', 'Empresa Comercial de Software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1514, 'emdesoft', 'emdesoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1515, 'Emesoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1516, 'EMIS SRL', 'EMIS SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1517, 'EmprendeSOFT.SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1518, 'EmpujeSoft.SRL', 'EmpujeSoft.SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1519, 'ENC', 'E.N.C. ( New Computational Empire ) S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1520, 'Enterprise software SRL', 'ENTERSOFT', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1521, 'Enterprise-esc', 'Enterprise Software Construction SA', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1522, 'EPIC', 'EPIC SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1523, 'ES3', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1524, 'ESA', 'ESA', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1525, 'ESSI', 'ESSI SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1526, 'ETIS', 'ETIS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1527, 'ETSI', 'ETSI', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1528, 'Evil Genius', 'Evil Genius S.R.L', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1529, 'Evil Genius SRL', 'EGENIUS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1530, 'Evolutionsoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1531, 'Ewebshop', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1532, 'eXistenZ', 'eXistenZ', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1533, 'Exodus', 'Exodus SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1534, 'Extreme System', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1535, 'F01 emdes', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1536, 'Falcon', 'Falcon Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1537, 'Faro Systems', 'Faro Systems', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1538, 'FDS', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1539, 'Fenix', 'Fenix', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1540, 'FenrirSulven Sistems. Ingenieria y Reingenieria', 'FenrirSulven Sistems. Ingenieria y Reingenieria', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1541, 'Feral Consultores.SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1542, 'Filia', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1543, 'FJSOFT', 'FJSOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1544, 'Flare Soft S.R.L.', 'Flare Soft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1545, 'Flash', 'Flash', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1546, 'FocaSoft', 'FocaSoft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1547, 'Formato X S.A.', 'Formato X S.A.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1548, 'Fox-Soft', 'Fox-Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1549, 'FRAMTIS', 'FRAMTIS SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1550, 'FreeSOFT.SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1551, 'FREEVALU', 'FreeValue SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1552, 'FRIENDSOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1553, 'Full Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1554, 'FUTESOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1555, 'G & G Soft', 'G & G Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1556, 'G Kaisoft', 'Group Knowledge Advanced In Innovation Of Software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1557, 'GDESIS', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1558, 'Gdesis', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1559, 'GDSOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1560, 'GEDSIS', 'GEDSIS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1561, 'GEDSOFT SA', 'Grupo de Desarrollo de Software Sociedad Anónima', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1562, 'GeekSlate', 'GeekSlate SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1563, 'Gen Soft', 'Generadores de software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1564, 'Generic software', 'Generic software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1565, 'Genesis', 'Genesis', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1566, 'Genesis Code', 'Genesis Code', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1567, 'Genesis Soft', 'Genesis Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1568, 'GeniusTech', 'GeniusTechnology S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1569, 'GERF', 'GERF Software S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1570, 'Ghost SRL', 'Ghost SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1571, 'Girasolmax', 'Girasolmax', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1572, 'GleakSoft', 'GleakSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1573, 'Global Soft', 'Global soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1574, 'Global Systems S.R.L.', 'Global Systems S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1575, 'Gos', 'Gos', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1576, 'GRED Soft', 'GRED Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1577, 'Grusoft_necs', 'Grusoft_necs', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1578, 'GTI Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1579, 'Guess Soft', 'Guess Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1580, 'Guss', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1581, 'HadesSoft', 'HadesSoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1582, 'Hellsoft', 'HELLSOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1583, 'Hexacode Technology', 'Hexacode Technology S.R.L. ', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1584, 'High Bits', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1585, 'House Soft.SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1586, 'Hsd', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1587, 'Huayra Soft', 'Huayra', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1588, 'Hypersoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1589, 'IART', 'Informatica Adelantos Responsables en Tecnologia', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1590, 'Iarte', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1591, 'Icarsoft Soluciones Tecnologicas', 'ICARSOFT', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1592, 'Icarus SRL', 'Icarus Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1593, 'Icon', 'icon soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1594, 'ICOS', 'Ingenieria de Computación y Software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1595, 'ID Soft SRL', 'ID Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1596, 'ide@', 'ide@', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1597, 'IKKITOUSEN SRL', 'IKKITOUSEN SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1598, 'Illimani', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1599, 'ILLUSION', 'ILLUSION SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1600, 'Imagsoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1601, 'INCA', 'INCA', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1602, 'INDESOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1603, 'Indesoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1604, 'INDEX SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1605, 'INFIDES SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1606, 'INFINITY CODE', 'INFINITY CODE Ltda.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1607, 'Infotec', 'Infotec', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1608, 'Infsis', 'Infsis', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1609, 'Infsol', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1610, 'Ingesof', 'Ingesof', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1611, 'INNER Soft', 'INNER Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1612, 'INNOSIS', 'Innovaciones en Sistemas Informáticos', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1613, 'INNOVA TECHNOLOGY SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1614, 'INNOVATE SRL', 'INNOVATE SOFTWARE SOLUTION SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1615, 'Innovatek', 'Innovatek SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1616, 'INNOVATION SOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1617, 'INNSER', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1618, 'INsoft', 'INsoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1619, 'InterfaceMultimedia', 'Interface Multimedia', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1620, 'Inti SRL', 'Inti SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1621, 'IRDB', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1622, 'Iridium', 'Iridium Software SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1623, 'Iridium SS', 'Iridium SOftware Solutions', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1624, 'Iron', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1625, 'IS', 'Innova Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1626, 'ISIS cia', 'ISIS cia', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1627, 'iSoft SRL', 'iSOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1628, 'ISSI', 'ISSI', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1629, 'ITEC', 'ITEC Innovación Tecnológica', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1630, 'ITG SRL', 'ITG SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1631, 'ITTEAM Ltda', 'Equipo de Tecnologias de información', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1632, 'ITTERASOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1633, 'Izzysoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1634, 'JAC', 'JAC', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1635, 'Jadesoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1636, 'Jaguar Soft. SRL', 'Jaguar Soft. SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1637, 'JAM', 'JAM Soft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1638, 'JAVAS Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1639, 'Javas Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1640, 'JAZC Development', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1641, 'JCSOFT', 'JCSOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1642, 'JetSoft', 'JetSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1643, 'JeveSoft', 'JeveSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1644, 'jexasoft', 'jexasoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1645, 'JH3', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1646, 'JMMSoft', 'JMMSoft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1647, 'Jugs', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1648, 'JUKUMARI', 'KD. SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1649, 'K-Lite Srl', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1650, 'KAHE', 'KAHE', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1651, 'KANE SRL', 'Informatic´s System´s Development KANE SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1652, 'KD', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1653, 'Kdes', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1654, 'KERNELOGICS', 'KERNELOGICS SOFTWARE SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1655, 'Kiwi', 'Kiwi is web investigation S.A.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1656, 'Knowledge Overload', 'Knowledge Overload', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1657, 'Koliita developers SRL', 'Kollita SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1658, 'Konoha Srl', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1659, 'KusaSoft', 'KusaSoft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1660, 'Lanv Solutions', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1661, 'Lemaxsoft', 'lemaxsoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1662, 'LETIS SRL', 'Lideres emprendedores en trabajos de ingenieria de software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1663, 'LEVEL SOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1664, 'LevitaSoft S.R.L.', 'Levita Software Development Technology Company S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1665, 'Lid systems', 'Lid systems', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1666, 'Lidere Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1667, 'LigthSoft', 'LigthSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1668, 'Linfocitos SRL.', 'Linfocitos SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1669, 'LionTech', 'LionTech.SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1670, 'Lirium SRL', 'Lirium Software Engineering Services SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1671, 'LITTLE SOLUTIONS', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1672, 'LiveCorp SRL', 'LiveCorp SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1673, 'Lizardtech', 'Lizardtech SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1674, 'LJSE', 'LJSE', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1675, 'Llajta Soft', 'Llajta Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1676, 'Lobel', 'Lobel', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1677, 'Logitech', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1678, 'Lynx', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1679, 'MachineSoft SRL', 'MachineSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1680, 'MACROSOFT', 'MACROSOFT', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1681, 'Macross', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1682, 'MAD SRL', 'MAD SOFT', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1683, 'MAGIC', 'Manejo Global de Información Computarizada', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1684, 'MagicLeague', 'MagicLeague SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1685, 'MagicTech', 'MagicTech.SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1686, 'Magio', 'MagioSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1687, 'MagoSoft', 'MagoSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1688, 'MAISOFT', 'MAISOFT S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1689, 'MANAGERSOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1690, 'Manzanares', 'Manzanares SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1691, 'Marfil SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1692, 'Marte', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1693, 'Maveric', 'maveric system', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1694, 'Maximal', 'Maximal Express S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1695, 'MBKM Soft', 'MBKM Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1696, 'McCorvi SRL', 'McCorvi SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1697, 'MD Futuro Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1698, 'Mega_Soft', 'Mega_Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1699, 'Mercury SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1700, 'MIChi - Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1701, 'Milenium SC', 'Milenium SC', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1702, 'MindCoding SRL', 'MindCoding SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1703, 'MindSoft S.R.L.', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1704, 'MingSoft SRL', 'MingSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1705, 'Mirasoft', 'Mirasoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1706, 'Miski Devs', 'Miski Devs', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1707, 'Molecular Soft', 'Molecular Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1708, 'Monkey developers SRL', 'Monkey', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1709, 'Moonsoft', 'Moonsoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1710, 'Munay Technology SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1711, 'Mundo Soft SRL', 'Empresa de Desarrollo de Sistemas Informáticos Mundo Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1712, 'MythicalSoft', 'MythicalSoft.SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1713, 'NaviSoft', 'NaviSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1714, 'Nemesis', 'Nemesis SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1715, 'Neolancer', 'Neolancer S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1716, 'NeoSoft SRL', 'NeoSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1717, 'Neptuno soft', 'Neptuno soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1718, 'NerdWare SRL', 'Nerd Software Engineering Services', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1719, 'NERF DATA', 'NERF DATA S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1720, 'NETSKY', 'NETSKY SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1721, 'NetSoft', 'NetSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1722, 'Network', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1723, 'Neurolink SRL', 'Neurolink SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1724, 'New Tech Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1725, 'NEXGEN SOFT S.R.L.', 'Next Generation Software S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1726, 'Nexsis', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1727, 'Nexus', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1728, 'NFS', 'NFS SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1729, 'Notepad', 'Notepad Coders S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1730, 'Novasoft', 'Novasoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1731, 'NSB_Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1732, 'Oasis', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1733, 'Olimpos', 'Olimpo´s Software System Designer', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1734, 'OMEGA SD', 'OMEGA Software Development', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1735, 'ON SOFT', 'Camaleon Software SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1736, 'OnBuilding Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1737, 'OpenMind Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1738, 'Orange Soft SRL', 'Orange Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1739, 'Oreosoft', 'OREOSOFT S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1740, 'Oriansoft', 'oriansoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1741, 'ORION SOFT', 'ORION SOFTWARE SOLUTIONS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1742, 'Osiris', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1743, 'Oversoft', 'oversoft desarrollando soluciones', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1744, 'Padsoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1745, 'Paradise', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1746, 'Pathfinder', 'Pathfinder', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1747, 'Pentamix', 'Pentamix', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1748, 'Pentasoft', 'Pentasoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1749, 'PEOPLE XTREME SOFT-PXP S.R.L.', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1750, 'PF', 'Programando el Futuro', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1751, 'Phalcondev', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1752, 'Phoenix SRL.', 'Phoenix SRL.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1753, 'Phpsoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1754, 'Pied S.R.L.', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1755, 'Pirasoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1756, 'Programadores sin límites.Srl', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1757, 'Propersoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1758, 'Prosoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1759, 'PSS', 'Prime Soft Solutions Ltda.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1760, 'PUNTO CLICK SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1761, 'Puriskiri', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1762, 'PYXIDIS', 'pyxidis solutions SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1763, 'Qbetagroup', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1764, 'Quality', 'Quality', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1765, 'QueIdeas Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1766, 'QuickSoftware S.R.L.', 'QuickSoftware S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1767, 'QUIRKYSOFT SRL', 'QUIRKYSOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1768, 'Ragosoft', 'Ragosoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1769, 'Ramon Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1770, 'Reactive Solutions.SRL', 'Reactive Solutions.SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1771, 'Resource Technology', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1772, 'Revolution Software', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1773, 'Ric_tis', 'Ric_tis', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1774, 'RobSoft', 'RobSoft Corporation', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1775, 'Ruasun_soft', 'Ruasun_soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1776, 'RVGC Soft', 'Roman Vargas Gonzales Chipana Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1777, 'S-XTREMES', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1778, 'S.R.L.', 'Consultora de Tecnologias de Ingenieria de Software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1779, 'SAADS SRL', 'SAADS SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1780, 'Sac', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1781, 'Sadi', 'Servicios de Automatizacion y desarrollo industrial', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1782, 'Sajom Soft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1783, 'SAS', 'Smart ACtion Software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1784, 'SAT', 'SAT', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1785, 'SCAYNET', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1786, 'ScrumTroopers S.C.', 'ScrumTroopers Sociedad Colectiva', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1787, 'SDC SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1788, 'SDSC', 'Sociedad de Desarrollo de Software de Calidad', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1789, 'Sed', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1790, 'SEE', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1791, 'SEGINFA', 'Seguridad Informática ALIENS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1792, 'Semael', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1793, 'SER SRL', 'Software Engineering Revolution SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1794, 'SerApps', 'SerApps SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1795, 'Servicios Integrales en Tecnología, Información y Computacion ', 'SITIC', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1796, 'ServiSoft.SRL', 'ServiSoft.SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1797, 'SETIC', 'SETIC', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1798, 'Sewbs SRL', 'Sewbs SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1799, 'SEWS', 'Software Engineering Work Shop', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1800, 'SHB', 'Software Hecho en Bolivia', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1801, 'Shiba Tech', 'Shiba Tech S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1802, 'ShieldCode Soft S.R.L', 'ShieldCode Soft S.R.L', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1803, 'SHIFT SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1804, 'SHYAB', 'SHYAB', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1805, 'SIAN SRL', 'SIAN SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1806, 'Sibosoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1807, 'SICC', 'SICC', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1808, 'SICESOFT SRL.', 'SOLUTIONS ICE SOFTWARE SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1809, 'Sicomp', 'Sicomp', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1810, 'SID SRL', 'SID SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1811, 'SIDA', 'SIDA', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1812, 'SIDESOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1813, 'Sigma', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1814, 'SimCom', 'SimCom', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1815, 'Simplicity', 'Simplicity', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1816, 'Simus', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1817, 'SING', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1818, 'SINGECORP', 'Sistemas Informaticos de Gestion Corporativa', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1819, 'SINTEG', 'Solución Inteligente de Tecnologia Global S.R.L', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1820, 'SISCO', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1821, 'SISNET', 'Sistemas Informáticos Seguros en Internet,', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1822, 'Sispreco SRL', 'Sispreco SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1823, 'SISU', 'Sistemas de SOftware Unidos', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1824, 'SITEC', 'SIstemas de Informacion Tecnologica', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1825, 'SIWEB', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1826, 'Sky Brians', 'Sky Brians SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1827, 'SKYNET', 'SKYNET', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1828, 'SKYSOFT', 'SKYSOFT SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1829, 'SLOW CODE', 'SLOW CODE SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1830, 'Smart Solution', 'Smart Solution S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1831, 'Smartsoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1832, 'SnoopySoft', 'SnoopySoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1833, 'SODES SRL', 'Software Development Enterprise SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1834, 'SODESI SRL', 'SODESI SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1835, 'Soft Llajta', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1836, 'SOFT MAGIC TOUCH', 'SOFTWARE MAGIC TOUCH', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1837, 'Soft Master', 'Soft Master', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1838, 'SOFT NET Ltda.', 'Empresa de desarrollo de software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1839, 'Soft Source', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1840, 'Soft World', 'Soluciones integrales con tecnología simplificada', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1841, 'SOFT_LAB S.R.L.', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1842, 'SOFT_SOURCE', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1843, 'SoftART', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1844, 'SoftBar', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1845, 'Softbol', 'Softbol', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1846, 'SoftBox Soluciones', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1847, 'SoftCode', 'SoftCode SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1848, 'Softcreme', 'Softcreme SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1849, 'SOFTDEITEL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1850, 'SoftInnovate Solutions', 'SoftInnovate Solutions SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1851, 'Softelligent', 'SOFTWARE INTELIGENTE', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1852, 'SOFTG', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1853, 'SOFTIS', 'Software TIS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1854, 'SoftLab S.R.L.', 'SoftLab S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1855, 'SoftMakers', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1856, 'Softop', 'Softop', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1857, 'Softquina', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1858, 'SoftServ', 'Software Service', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1859, 'SoftSolutions', 'SoftSolutions SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1860, 'SoftVision', 'The Software Vision Company', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1861, 'Software Development Innovation SRL', 'SDI SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1862, 'Softwaredesigners', 'software designers SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1863, 'SoftWib', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1864, 'Soinco', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1865, 'Solid Developers SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1866, 'Solidev', 'Solidev S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1867, 'SOLUSOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1868, 'SOLVWARE', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1869, 'SOTEA SRL', 'SOTEA SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1870, 'SotwareEnpreneur', 'SotwareEnpreneur SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1871, 'Source Code', 'Source Code', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1872, 'Space', 'Space SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1873, 'SPYD Software', 'Sociedad de Planificación Y Desarrollo de Software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1874, 'Sss', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1875, 'StardustSoft', 'StardustSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1876, 'STARTSOFT', 'Empresa de Desarrollo Informatico STARTSOFT', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1877, 'STARTTIS', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1878, 'Sting Soft SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1879, 'Storm', 'StormSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1880, 'Stragos', 'Stragos soft srl', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1881, 'STS', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1882, 'StudSoft', 'StudSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1883, 'Sublime SRL', 'Sublime Projects SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1884, 'SumajSoft', 'Sumajsoft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1885, 'Summit', 'Summit SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1886, 'Swlink', 'Swlink', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1887, 'Symphony Soft', 'Symphony Software', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1888, 'Synapsis', 'Synapsis', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1889, 'Synchro SRL', 'Synchro SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1890, 'SynergiSoft', 'SynergiSoft S.R.L', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1891, 'Sysdecom', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1892, 'SystemBolDevSoft Srl', 'SystemBolDevSoft Srl', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1893, 'SystemWorks', 'SystemWorks SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1894, 'T-SYS', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1895, 'TALOS Dev', 'Talos Development S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1896, 'TBS', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1897, 'TDsoft', 'TDsoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1898, 'TeachBird', 'TeachBird SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1899, 'Team Soft', 'Team Soft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1900, 'TEC', 'TEC', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1901, 'TECASOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1902, 'TecnoAvance', 'TecnoAvance', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1903, 'Tecnology', 'Tecnology soft ltda', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1904, 'TeleTran', 'TeleTran', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1905, 'TeraSoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1906, 'TH', 'Transhumant', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1907, 'The Code Tellers', 'The Code Tellers SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1908, 'ThinkDSoft SRL', 'ThinkDSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1909, 'THNS SRL', 'Technohookup Newsystems SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1910, 'THREEFORCE DEVELOPMENT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1911, 'ThunderSoft', 'Thunder Software S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1912, 'TI SOLUTUONS', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1913, 'TIM.SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1914, 'TISOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1915, 'TIZEN', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1916, 'TopCoDev.SRL', 'TopCoDev.SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1917, 'TopSoft', 'Top Software SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1918, 'Totality', 'Totality', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1919, 'TOTEMWORKS', 'TOTEMWORKS', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1920, 'Trinity Soft', 'Trinity Software Development', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1921, 'Trojan Soft', 'Trojan Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1922, 'Trust Quest SRL', 'Trust Quest SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1923, 'TRY TECK S.R.L.', 'TRY TECK S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1924, 'TS SRL', 'Team Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1925, 'Tunari.com', 'Tunari.com', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1926, 'TuringSoft.S.R.L', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1927, 'ULTIMATE', 'ULTIMATE', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1928, 'Umbrella', 'Umbrella CORP SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1929, 'Umbrella Code', 'Umbrella Code SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1930, 'Unisoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1931, 'Unlocking Software', 'Unlocking SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1932, 'UNTEC', 'Undefined Technology S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1933, 'Urban Soft SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1934, 'Usoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1935, 'V@gos soft SRL', 'V@gos soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1936, 'Valle Soft', 'Valle Soft  S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1937, 'VenSoft SRL', 'VenSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1938, 'venturesome', 'venturesome', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1939, 'Viba', 'Viba', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1940, 'VIDA SRL', 'VIDA SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1941, 'Virtu@l soft', 'Virtu@l soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1942, 'VirusNot', 'VirusNot Development Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1943, 'Waarp', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1944, 'Wayra', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1945, 'WebJets', 'WebJets Soluciones informaticas', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1946, 'WebOn', 'WebOn SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1947, 'WEBSOLUTIONS', 'WEBSOLUTIONS SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1948, 'WEsoft', 'WEsoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1949, 'Whitehatsoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1950, 'WHS SRL', 'Work at Home Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1951, 'WieselSoft SRL', 'WieselSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1952, 'Winesoft', 'Winesoft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1953, 'WinnSoft', 'WinnSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1954, 'Winsmart Soft.SRL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1955, 'WOLF', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1956, 'X-SOFT', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1957, 'XINTHEWORLD', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1958, 'XPARSA', 'EXPANDIENDO SOFTWARE', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1959, 'XPDEV', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1960, 'Xpro', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1961, 'Xsoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1962, 'Xtreme SB SRL', 'Xtreme StormBrain SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1963, 'XtremeSoft', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1964, 'YAC', 'Yac ingenieria de calidad', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1965, 'Yachay', 'YachayPacha Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1966, 'Yantana Soft', 'Yantana Soft', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1967, 'YELADEVEL', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1968, 'Yenci Soft', 'Yenci Soft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1969, 'YUME', null, null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1970, 'ZEIKO', 'ZEIKO SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1971, 'Zeros & Ones SRL', 'Zeros & Ones SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1972, 'Zeus', 'ZEUS SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1973, 'Zion', 'Zion', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1974, 'ZODIAC', 'ZODIAC S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1975, 'B.F.S.', 'Brute Force Solutions', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1976, 'Digital Nest', 'Digital Nest S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1977, 'Intelligence Software', 'Intelligence Software S.R.L', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1978, 'JaCOD', 'Jatun Code Tecnología', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1979, 'Llama Digital', 'Llama Digital – making life easier S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1980, 'PhilfrutSoft', 'PhilfrutSoft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1981, 'SkynetSoft', 'Skynet Development Soft S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1982, 'Steel Code', 'Steel Code S.R.L', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1983, 'Zincronix', 'Zincronix Solutions S.R.L.', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1984, 'DevGenius', 'DevGenius SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1985, 'DreamSoft', 'DreamSoft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1986, 'Eureka Solutions', 'Eureka Solutions SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1987, 'MegaByte', 'MegaByte SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1988, 'Purple Soft', 'Purple Soft SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1989, 'Ada Enterprise', 'Ada Enterprise SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1990, 'SparkCode', 'SparkCode SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1991, 'IBM Jr', 'IBM Jr SRL', null, null);
INSERT INTO public.group_names (id, short_name, long_name, created_at, updated_at) VALUES (1992, 'Palmer Technology', 'Palmer Technology SRL', null, null);
